pom 49 | modified deploy job in build and publish to list pwd

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -30,94 +30,94 @@ env:
 
 jobs:
 
-  docker-build-publish:
-    name: Docker Build & Publish
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.build == 'true' }}
-    steps:
-      - name: Pull Github code
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.inputs.branch }}
+#   docker-build-publish:
+#     name: Docker Build & Publish
+#     runs-on: ubuntu-latest
+#     if: ${{ github.event.inputs.build == 'true' }}
+#     steps:
+#       - name: Pull Github code
+#         uses: actions/checkout@v2
+#         with:
+#           ref: ${{ github.event.inputs.branch }}
 
-      - name: Configure AWS Credentials
-        if: ${{ github.event.inputs.environment == 'qa' }}
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+#       - name: Configure AWS Credentials
+#         if: ${{ github.event.inputs.environment == 'qa' }}
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Configure AWS Credentials
-        if: ${{ github.event.inputs.environment == 'staging' }}
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+#       - name: Configure AWS Credentials
+#         if: ${{ github.event.inputs.environment == 'staging' }}
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Configure AWS Credentials
-        if: ${{ github.event.inputs.environment == 'production' }}
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.PROD_AWS_REGION }}
+#       - name: Configure AWS Credentials
+#         if: ${{ github.event.inputs.environment == 'production' }}
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ secrets.PROD_AWS_REGION }}
 
-      - name: Login to AWS ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
+#       - name: Login to AWS ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v2
 
-      - name: Set Image tag variable
-        run: |
-          pwd
-          echo $GITHUB_RUN_NUMBER
-          echo "ARTIFACT_VERSION=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
-          echo $GITHUB_WORKSPACE
+#       - name: Set Image tag variable
+#         run: |
+#           pwd
+#           echo $GITHUB_RUN_NUMBER
+#           echo "ARTIFACT_VERSION=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
+#           echo $GITHUB_WORKSPACE
 
-#      - name: Build and Push Docker Image to ECR
-#        env:
-#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-#          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
-#        run: |
-#          IFS=',' read -ra IMAGE_ARRAY <<< "${IMAGE_NAMES}"
-#          for IMAGE in "${IMAGE_ARRAY[@]}"; do
-#            export IMAGE_NAME=$IMAGE
-#            /docker/build.sh $IMAGE_NAME -t $IMAGE_TAG -r $ECR_REGISTRY
-#          done
+# #      - name: Build and Push Docker Image to ECR
+# #        env:
+# #          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+# #          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
+# #        run: |
+# #          IFS=',' read -ra IMAGE_ARRAY <<< "${IMAGE_NAMES}"
+# #          for IMAGE in "${IMAGE_ARRAY[@]}"; do
+# #            export IMAGE_NAME=$IMAGE
+# #            /docker/build.sh $IMAGE_NAME -t $IMAGE_TAG -r $ECR_REGISTRY
+# #          done
 
-      - name: Build and Push Docker Image to ECR
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
-        run: |
-          IMAGE_LIST=$(./docker/build.sh "${IMAGE_NAMES}" -r "${ECR_REGISTRY}" -t "${IMAGE_TAG}")
-          # Save the list of images to a file
-          echo "$IMAGE_LIST" > image-names.txt
+#       - name: Build and Push Docker Image to ECR
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
+#         run: |
+#           IMAGE_LIST=$(./docker/build.sh "${IMAGE_NAMES}" -r "${ECR_REGISTRY}" -t "${IMAGE_TAG}")
+#           # Save the list of images to a file
+#           echo "$IMAGE_LIST" > image-names.txt
 
-      - name: Save Image Names as Artifact
-        if: always()
-        run: |
-          # Ensure the file exists before attempting to save it as an artifact
-          if [ -f "image-names.txt" ]; then
-            cat image-names.txt
-          else
-            echo "Image names file not found."
-            exit 1
-          fi
-        working-directory: ${{ github.workspace }}
+#       - name: Save Image Names as Artifact
+#         if: always()
+#         run: |
+#           # Ensure the file exists before attempting to save it as an artifact
+#           if [ -f "image-names.txt" ]; then
+#             cat image-names.txt
+#           else
+#             echo "Image names file not found."
+#             exit 1
+#           fi
+#         working-directory: ${{ github.workspace }}
 
-      # Upload the file as an artifact
-      - name: Upload Image Names Artifact
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: image-names
-          path: image-names.txt
+#       # Upload the file as an artifact
+#       - name: Upload Image Names Artifact
+#         if: always()
+#         uses: actions/upload-artifact@v2
+#         with:
+#           name: image-names
+#           path: image-names.txt
 
   deploy:
     runs-on: ubuntu-latest
-    needs: docker-build-publish
+    # needs: docker-build-publish
     if: ${{ github.event.inputs.deploy == 'true' }}
 
     steps:
@@ -138,12 +138,16 @@ jobs:
           IMAGE_NAMES=$(cat /tmp/image-names.txt)
           echo "$IMAGE_NAMES=${IMAGE_NAMES}" >> $GITHUB_OUTPUT
 
+      - name: check directory
+        run: |
+          pwd
+          ls -la
 
       - name: Trigger Deploy Workflow
         uses: ./.github/workflows/deploy-ecs.yml
-        with:
-          environment: ${{ github.event.inputs.environment }}
-          branch: ${{ github.event.inputs.branch }}
+        # with:
+        #   environment: ${{ github.event.inputs.environment }}
+        #   branch: ${{ github.event.inputs.branch }}
 
 
       # - name: Deploy to Amazon ECS
